# Generated by Django 6.1 on 2026-08-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='RUB', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Укажите описание', max_length=1000, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('created', 'создано'), ('processing', 'в процессе'), ('completed', 'исполнено'), ('rejected', 'отклонено')], default='created', max_length=255)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment operation',
                'verbose_name_plural': 'Payment operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmitIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='payment_gateway.operation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='payment_gateway.operation')),
            ],
            options={
                'ordering': ['event_id'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'event_id'), name='unique_event_per_operation')],
            },
        ),
    ]
