# Generated by Django 6.1 on 2026-08-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'создано'), ('PROCESSING', 'в процессе'), ('COMPLETED', 'исполнено'), ('REJECTED', 'отклонено')], default='CREATED', max_length=255),
        ),
        migrations.AlterField(
            model_name='operationevent',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payment_gateway.operation'),
        ),
    ]
